# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


quote_list = [
["The game has its ups and downs, but you can never lose focus of your individual goals and you can't let yourself be beat because of lack of effort.", "Michael Jordan" ],
["I've missed more than 9000 shots in my career. I've lost almost 300 games. 26 times, I've been trusted to take the game winning shot and missed. I've failed over and over and over again in my life. And that is why I succeed.", "Michael Jordan" ],
["If you're trying to achieve, there will be roadblocks. I've had them; everybody has had them. But obstacles don't have to stop you. If you run into a wall, don't turn around and give up. Figure out how to climb it, go through it, or work around it.", "Michael Jordan" ],
["If you accept the expectations of others, especially negative ones, then you never will change the outcome.", "Michael Jordan" ],
["I've failed over and over and over again in my life and that is why I succeed.", "Michael Jordan" ],
["My attitude is that if you push me towards something that you think is a weakness, then I will turn that perceived weakness into a strength.", "Michael Jordan" ],
["I can accept failure, everyone fails at something. But I can't accept not trying.", "Michael Jordan" ],
["Some people want it to happen, some wish it would happen, others make it happen.", "Michael Jordan" ],
["Always turn a negative situation into a positive situation.", "Michael Jordan" ],
["To be successful you have to be selfish, or else you never achieve. And once you get to your highest level, then you have to be unselfish. Stay reachable. Stay in touch. Don't isolate.", "Michael Jordan" ],
["Talent wins games, but teamwork and intelligence wins championships.", "Michael Jordan" ],
["Obstacles don't have to stop you. If you run into a wall, don't turn around and give up. Figure out how to climb it, go through it, or work around it.", "Michael Jordan" ],
["Just play. Have fun. Enjoy the game.", "Michael Jordan" ],
["My heroes are and were my parents. I can't see having anyone else as my heroes.", "Michael Jordan" ],
["I play to win, whether during practice or a real game. And I will not let anything get in the way of me and my competitive enthusiasm to win.", "Michael Jordan" ],
["The game is my wife. It demands loyalty and responsibility, and it gives me back fulfillment and peace.", "Michael Jordan" ],
["My father used to say that it's never too late to do anything you wanted to do. And he said, 'You never know what you can accomplish until you try.'", "Michael Jordan" ],
["The game of basketball has been everything to me. My place of refuge, place I've always gone where I needed comfort and peace. It's been the site of intense pain and the most intense feelings of joy and satisfaction. It's a relationship that has evolved over time, given me the greatest respect and love for the game.", "Michael Jordan" ],
["I've always believed that if you put in the work, the results will come.", "Michael Jordan" ],
["As athletes, we're used to reacting quickly. Here, it's 'come, stop, come, stop.' There's a lot of downtime. That's the toughest part of the day.", "Michael Jordan" ],
["There is no such thing as a perfect basketball player, and I don't believe there is only one greatest player either.", "Michael Jordan" ],
["You have to expect things of yourself before you can do them.", "Michael Jordan" ],
["I never looked at the consequences of missing a big shot... when you think about the consequences you always think of a negative result.", "Michael Jordan" ],
["When I lose the sense of motivation and the sense to prove something as a basketball player, it's time for me to move away from the game.", "Michael Jordan" ],
["I've never been afraid to fail.", "Michael Jordan" ],
["The game has its ups and downs, but you can never lose focus of your individual goals and you can't let yourself be beat because of lack of effort.", "Michael Jordan" ],
["Success is a lousy teacher. It seduces smart people into thinking they can't lose.", "Bill Gates" ],
["It's fine to celebrate success but it is more important to heed the lessons of failure.", "Bill Gates" ],
["If you can't make it good, at least make it look good.", "Bill Gates" ],
["Technology is just a tool. In terms of getting the kids working together and motivating them, the teacher is the most important.", "Bill Gates" ],
["Your most unhappy customers are your greatest source of learning.", "Bill Gates" ],
["I believe that if you show people the problems and you show them the solutions they will be moved to act.", "Bill Gates" ],
["I'm a great believer that any tool that enhances communication has profound effects in terms of how people can learn from each other, and how they can achieve the kind of freedoms that they're interested in.", "Bill Gates" ],
["The first rule of any technology used in a business is that automation applied to an efficient operation will magnify the efficiency. The second is that automation applied to an inefficient operation will magnify the inefficiency.", "Bill Gates" ],
["As we look ahead into the next century, leaders will be those who empower others.", "Bill Gates" ],
["I really had a lot of dreams when I was a kid, and I think a great deal of that grew out of the fact that I had a chance to read a lot.", "Bill Gates" ],
["Just in terms of allocation of time resources, religion is not very efficient. There's a lot more I could be doing on a Sunday morning.", "Bill Gates" ],
["If GM had kept up with technology like the computer industry has, we would all be driving $25 cars that got 1,000 MPG.", "Bill Gates" ],
["Well the protester I think is a very powerful thing. It's basically a mechanism of democracy that, along with capitalism, scientific innovation, those things have built the modern world. And it's wonderful that the new tools have empowered that protestor so that state secrets, bad developments are not hidden anymore.", "Bill Gates" ],
["At Microsoft there are lots of brilliant ideas but the image is that they all come from the top - I'm afraid that's not quite right.", "Bill Gates" ],
["I think it's fair to say that personal computers have become the most empowering tool we've ever created. They're tools of communication, they're tools of creativity, and they can be shaped by their user.", "Bill Gates" ],
["We always overestimate the change that will occur in the next two years and underestimate the change that will occur in the next ten. Don't let yourself be lulled into inaction.", "Bill Gates" ],
["People always fear change. People feared electricity when it was invented, didn't they? People feared coal, they feared gas-powered engines... There will always be ignorance, and ignorance leads to fear. But with time, people will come to accept their silicon masters.", "Bill Gates" ],
["640K ought to be enough for anybody.", "Bill Gates" ],
["I actually thought that it would be a little confusing during the same period of your life to be in one meeting when you're trying to make money, and then go to another meeting where you're giving it away. I mean is it gonna erode your ability, you know, to make money? Are you gonna somehow get confused about what you're trying to do?", "Bill Gates" ],
["Information technology and business are becoming inextricably interwoven. I don't think anybody can talk meaningfully about one without the talking about the other.", "Bill Gates" ],
["In this business, by the time you realize you're in trouble, it's too late to save yourself. Unless you're running scared all the time, you're gone.", "Bill Gates" ],
["Intellectual property has the shelf life of a banana.", "Bill Gates" ],
["The Internet is becoming the town square for the global village of tomorrow.", "Bill Gates" ],
["If I'd had some set idea of a finish line, don't you think I would have crossed it years ago?", "Bill Gates" ],
["Until we're educating every kid in a fantastic way, until every inner city is cleaned up, there is no shortage of things to do.", "Bill Gates" ],
["I love those who can smile in trouble, who can gather strength from distress, and grow brave by reflection. 'Tis the business of little minds to shrink, but they whose heart is firm, and whose conscience approves their conduct, will pursue their principles unto death.", "Leonardo da Vinci" ],
["For once you have tasted flight you will walk the earth with your eyes turned skywards, for there you have been and there you will long to return.", "Leonardo da Vinci" ],
["It had long since come to my attention that people of accomplishment rarely sat back and let things happen to them. They went out and happened to things.", "Leonardo da Vinci" ],
["While I thought that I was learning how to live, I have been learning how to die.", "Leonardo da Vinci" ],
["Life is pretty simple: You do some stuff. Most fails. Some works. You do more of what works. If it works big, others quickly copy it. Then you do something else. The trick is the doing something else.", "Leonardo da Vinci" ],
["Simplicity is the ultimate sophistication.", "Leonardo da Vinci" ],
["A well-spent day brings happy sleep.", "Leonardo da Vinci" ],
["The greatest deception men suffer is from their own opinions.", "Leonardo da Vinci" ],
["Art is never finished, only abandoned.", "Leonardo da Vinci" ],
["There are three classes of people: those who see, those who see when they are shown, those who do not see.", "Leonardo da Vinci" ],
["Nothing strengthens authority so much as silence.", "Leonardo da Vinci" ],
["As a well-spent day brings happy sleep, so a life well spent brings happy death.", "Leonardo da Vinci" ],
["I have been impressed with the urgency of doing. Knowing is not enough; we must apply. Being willing is not enough; we must do.", "Leonardo da Vinci" ],
["Why does the eye see a thing more clearly in dreams than the imagination when awake?", "Leonardo da Vinci" ],
["The noblest pleasure is the joy of understanding.", "Leonardo da Vinci" ],
["Marriage is like putting your hand into a bag of snakes in the hope of pulling out an eel.", "Leonardo da Vinci" ],
["Iron rusts from disuse; water loses its purity from stagnation... even so does inaction sap the vigor of the mind.", "Leonardo da Vinci" ],
["The human foot is a masterpiece of engineering and a work of art.", "Leonardo da Vinci" ],
["Blinding ignorance does mislead us. O! Wretched mortals, open your eyes!", "Leonardo da Vinci" ],
["Where the spirit does not work with the hand, there is no art.", "Leonardo da Vinci" ],
["Anyone who conducts an argument by appealing to authority is not using his intelligence; he is just using his memory.", "Leonardo da Vinci" ],
["Water is the driving force of all nature.", "Leonardo da Vinci" ],
["Where there is shouting, there is no true knowledge.", "Leonardo da Vinci" ],
["In rivers, the water that you touch is the last of what has passed and the first of that which comes; so with present time.", "Leonardo da Vinci" ],
["Learning never exhausts the mind.", "Leonardo da Vinci" ],
["The truth is you don't know what is going to happen tomorrow. Life is a crazy ride, and nothing is guaranteed.", "Eminem" ],
["I say what I want to say and do what I want to do. There's no in between. People will either love you for it or hate you for it.", "Eminem" ],
["Dealing with backstabbers, there was one thing I learned. They're only powerful when you got your back turned.", "Eminem" ],
["I am who I am and I say what I think. I'm not putting a face on for the record.", "Eminem" ],
["Trust is hard to come by. That's why my circle is small and tight. I'm kind of funny about making new friends.", "Eminem" ],
["I don't hate women - they just sometimes make me mad.", "Eminem" ],
["I am whatever you say I am; if I wasn't, then why would you say I am.", "Eminem" ],
["Somewhere deep down there's a decent man in me, he just can't be found.", "Eminem" ],
["To the people I forgot, you weren't on my mind for some reason and you probably don't deserve any thanks anyway.", "Eminem" ],
["I'm stupid, I'm ugly, I'm dumb, I smell. Did I mention I'm stupid?", "Eminem" ],
["It sometimes feels like a strange movie, you know, it's all so weird that sometimes I wonder if it is really happening.", "Eminem" ],
["My thing is this; if I'm sick enough to think it, then I'm sick enough to say it.", "Eminem" ],
["Say there's a white kid who lives in a nice home, goes to an all-white school, and is pretty much having everything handed to him on a platter - for him to pick up a rap tape is incredible to me, because what that's saying is that he's living a fantasy life of rebellion.", "Eminem" ],
["A lot of truth is said in jest.", "Eminem" ],
["My father? I never knew him. Never even seen a picture of him.", "Eminem" ],
["Sometimes I feel like rap music is almost the key to stopping racism.", "Eminem" ],
["I need drama in my life to keep making music.", "Eminem" ],
["These times are so hard, and they're getting even harder.", "Eminem" ],
["I always wished for this, but it's almost turning into more of a nightmare than a dream.", "Eminem" ],
["I might talk about killing people, but that doesn't mean I do it.", "Eminem" ],
["It'd be stupid for me to sit here and say that there aren't kids who look up to me, but my responsibility is not to them. I'm not a baby sitter.", "Eminem" ],
["Anybody with a sense of humor is going to put on my album and laugh from beginning to end.", "Eminem" ],
["If there's not drama and negativity in my life, all my songs will be really wack and boring or something.", "Eminem" ],
["I don't even know how to speak up for myself, because I don't really have a father who would give me the confidence or advice.", "Eminem" ],
["Nobody likes to fail. I want to succeed in everything I do, which isn't much. But the things that I'm really passionate about, if I fail at those, if I'm not successful, what do I have?", "Eminem" ],
["America will never be destroyed from the outside. If we falter and lose our freedoms, it will be because we destroyed ourselves.", "Abraham Lincoln" ],
["Better to remain silent and be thought a fool than to speak out and remove all doubt.", "Abraham Lincoln" ],
["Sir, my concern is not whether God is on our side; my greatest concern is to be on God's side, for God is always right.", "Abraham Lincoln" ],
["You can fool all the people some of the time, and some of the people all the time, but you cannot fool all the people all the time.", "Abraham Lincoln" ],
["Most folks are as happy as they make up their minds to be.", "Abraham Lincoln" ],
["Nearly all men can stand adversity, but if you want to test a man's character, give him power.", "Abraham Lincoln" ],
["In the end, it's not the years in your life that count. It's the life in your years.", "Abraham Lincoln" ],
["We the people are the rightful masters of both Congress and the courts, not to overthrow the Constitution but to overthrow the men who pervert the Constitution.", "Abraham Lincoln" ],
["Give me six hours to chop down a tree and I will spend the first four sharpening the axe.", "Abraham Lincoln" ],
["All that I am, or hope to be, I owe to my angel mother.", "Abraham Lincoln" ],
["Always bear in mind that your own resolution to succeed is more important than any other.", "Abraham Lincoln" ],
["This country, with its institutions, belongs to the people who inhabit it. Whenever they shall grow weary of the existing government, they can exercise their constitutional right of amending it, or exercise their revolutionary right to overthrow it.", "Abraham Lincoln" ],
["Character is like a tree and reputation like a shadow. The shadow is what we think of it; the tree is the real thing.", "Abraham Lincoln" ],
["Don't interfere with anything in the Constitution. That must be maintained, for it is the only safeguard of our liberties.", "Abraham Lincoln" ],
["Labor is prior to, and independent of, capital. Capital is only the fruit of labor, and could never have existed if labor had not first existed. Labor is the superior of capital, and deserves much the higher consideration.", "Abraham Lincoln" ],
["The best thing about the future is that it comes one day at a time.", "Abraham Lincoln" ],
["I am not bound to win, but I am bound to be true. I am not bound to succeed, but I am bound to live by the light that I have. I must stand with anybody that stands right, and stand with him while he is right, and part with him when he goes wrong.", "Abraham Lincoln" ],
["A friend is one who has the same enemies as you have.", "Abraham Lincoln" ],
["Government of the people, by the people, for the people, shall not perish from the Earth.", "Abraham Lincoln" ],
["I remember my mother's prayers and they have always followed me. They have clung to me all my life.", "Abraham Lincoln" ],
["Any people anywhere, being inclined and having the power, have the right to rise up, and shake off the existing government, and form a new one that suits them better. This is a most valuable - a most sacred right - a right, which we hope and believe, is to liberate the world.", "Abraham Lincoln" ],
["Am I not destroying my enemies when I make friends of them?", "Abraham Lincoln" ],
["Be sure you put your feet in the right place, then stand firm.", "Abraham Lincoln" ],
["I am a firm believer in the people. If given the truth, they can be depended upon to meet any national crisis. The great point is to bring them the real facts.", "Abraham Lincoln" ],
["No man is good enough to govern another man without the other's consent.", "Abraham Lincoln" ],
["Do not go where the path may lead, go instead where there is no path and leave a trail.", "Ralph Waldo Emerson" ],
["Write it on your heart that every day is the best day in the year.", "Ralph Waldo Emerson" ],
["All life is an experiment. The more experiments you make the better.", "Ralph Waldo Emerson" ],
["It is one of the blessings of old friends that you can afford to be stupid with them.", "Ralph Waldo Emerson" ],
["To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", "Ralph Waldo Emerson" ],
["For every minute you remain angry, you give up sixty seconds of peace of mind.", "Ralph Waldo Emerson" ],
["Adopt the pace of nature: her secret is patience.", "Ralph Waldo Emerson" ],
["What lies behind you and what lies in front of you, pales in comparison to what lies inside of you.", "Ralph Waldo Emerson" ],
["Our greatest glory is not in never failing, but in rising up every time we fail.", "Ralph Waldo Emerson" ],
["The age of a woman doesn't mean a thing. The best tunes are played on the oldest fiddles.", "Ralph Waldo Emerson" ],
["All I have seen teaches me to trust the creator for all I have not seen.", "Ralph Waldo Emerson" ],
["Peace cannot be achieved through violence, it can only be attained through understanding.", "Ralph Waldo Emerson" ],
["Nature always wears the colors of the spirit.", "Ralph Waldo Emerson" ],
["Love of beauty is taste. The creation of beauty is art.", "Ralph Waldo Emerson" ],
["The only way to have a friend is to be one.", "Ralph Waldo Emerson" ],
["Character is higher than intellect. A great soul will be strong to live as well as think.", "Ralph Waldo Emerson" ],
["It is not length of life, but depth of life.", "Ralph Waldo Emerson" ],
["Nobody can bring you peace but yourself.", "Ralph Waldo Emerson" ],
["You cannot do a kindness too soon, for you never know how soon it will be too late.", "Ralph Waldo Emerson" ],
["Men are what their mothers made them.", "Ralph Waldo Emerson" ],
["Once you make a decision, the universe conspires to make it happen.", "Ralph Waldo Emerson" ],
["Never lose an opportunity of seeing anything beautiful, for beauty is God's handwriting.", "Ralph Waldo Emerson" ],
["Shallow men believe in luck. Strong men believe in cause and effect.", "Ralph Waldo Emerson" ],
["Always do what you are afraid to do.", "Ralph Waldo Emerson" ],
["Though we travel the world over to find the beautiful, we must carry it with us or we find it not.", "Ralph Waldo Emerson" ],
["Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.", "Thomas A. Edison" ],
["Opportunity is missed by most people because it is dressed in overalls and looks like work.", "Thomas A. Edison" ],
["I have not failed. I've just found 10,000 ways that won't work.", "Thomas A. Edison" ],
["Many of life's failures are people who did not realize how close they were to success when they gave up.", "Thomas A. Edison" ],
["The reason a lot of people do not recognize opportunity is because it usually goes around wearing overalls looking like hard work.", "Thomas A. Edison" ],
["Genius is one percent inspiration and ninety-nine percent perspiration.", "Thomas A. Edison" ],
["I have friends in overalls whose friendship I would not swap for the favor of the kings of the world.", "Thomas A. Edison" ],
["Being busy does not always mean real work. The object of all work is production or accomplishment and to either of these ends there must be forethought, system, planning, intelligence, and honest purpose, as well as perspiration. Seeming to do is not doing.", "Thomas A. Edison" ],
["If we did all the things we are capable of, we would literally astound ourselves.", "Thomas A. Edison" ],
["Hell, there are no rules here - we're trying to accomplish something.", "Thomas A. Edison" ],
["To invent, you need a good imagination and a pile of junk.", "Thomas A. Edison" ],
["Non-violence leads to the highest ethics, which is the goal of all evolution. Until we stop harming all other living beings, we are still savages.", "Thomas A. Edison" ],
["There is no substitute for hard work.", "Thomas A. Edison" ],
["The three great essentials to achieve anything worth while are: Hard work, Stick-to-itiveness, and Common sense.", "Thomas A. Edison" ],
["Just because something doesn't do what you planned it to do doesn't mean it's useless.", "Thomas A. Edison" ],
["Restlessness is discontent and discontent is the first necessity of progress. Show me a thoroughly satisfied man and I will show you a failure.", "Thomas A. Edison" ],
["I never did a day's work in my life. It was all fun.", "Thomas A. Edison" ],
["Discontent is the first necessity of progress.", "Thomas A. Edison" ],
["Your worth consists in what you are and not in what you have.", "Thomas A. Edison" ],
["Be courageous. I have seen many depressions in business. Always America has emerged from these stronger and more prosperous. Be brave as your fathers before you. Have faith! Go forward!", "Thomas A. Edison" ],
["Everything comes to him who hustles while he waits.", "Thomas A. Edison" ],
["I never did anything by accident, nor did any of my inventions come by accident; they came by work.", "Thomas A. Edison" ],
["Anything that won't sell, I don't want to invent. Its sale is proof of utility, and utility is success.", "Thomas A. Edison" ],
["Maturity is often more absurd than youth and very frequently is most unjust to youth.", "Thomas A. Edison" ],
["There will one day spring from the brain of science a machine or force so fearful in its potentialities, so absolutely terrifying, that even man, the fighter, who will dare torture and death in order to inflict torture and death, will be appalled, and so abandon war forever.", "Thomas A. Edison" ],
["Someone is sitting in the shade today because someone planted a tree a long time ago.", "Warren Buffett" ],
["It takes 20 years to build a reputation and five minutes to ruin it. If you think about that, you'll do things differently.", "Warren Buffett" ],
["Rule No.1: Never lose money. Rule No.2: Never forget rule No.1.", "Warren Buffett" ],
["It's better to hang out with people better than you. Pick out associates whose behavior is better than yours and you'll drift in that direction.", "Warren Buffett" ],
["The rich are always going to say that, you know, just give us more money and we'll go out and spend more and then it will all trickle down to the rest of you. But that has not worked the last 10 years, and I hope the American public is catching on.", "Warren Buffett" ],
["Price is what you pay. Value is what you get.", "Warren Buffett" ],
["Wall Street is the only place that people ride to in a Rolls Royce to get advice from those who take the subway.", "Warren Buffett" ],
["I always knew I was going to be rich. I don't think I ever doubted it for a minute.", "Warren Buffett" ],
["Chains of habit are too light to be felt until they are too heavy to be broken.", "Warren Buffett" ],
["You do things when the opportunities come along. I've had periods in my life when I've had a bundle of ideas come along, and I've had long dry spells. If I get an idea next week, I'll do something. If not, I won't do a damn thing.", "Warren Buffett" ],
["Risk comes from not knowing what you're doing.", "Warren Buffett" ],
["Only when the tide goes out do you discover who's been swimming naked.", "Warren Buffett" ],
["I buy expensive suits. They just look cheap on me.", "Warren Buffett" ],
["The first rule is not to lose. The second rule is not to forget the first rule.", "Warren Buffett" ],
["I don't look to jump over 7-foot bars: I look around for 1-foot bars that I can step over.", "Warren Buffett" ],
["If anything, taxes for the lower and middle class and maybe even the upper middle class should even probably be cut further. But I think that people at the high end - people like myself - should be paying a lot more in taxes. We have it better than we've ever had it.", "Warren Buffett" ],
["You only have to do a very few things right in your life so long as you don't do too many things wrong.", "Warren Buffett" ],
["In the business world, the rearview mirror is always clearer than the windshield.", "Warren Buffett" ],
["Should you find yourself in a chronically leaking boat, energy devoted to changing vessels is likely to be more productive than energy devoted to patching leaks.", "Warren Buffett" ],
["When you combine ignorance and leverage, you get some pretty interesting results.", "Warren Buffett" ],
["Of the billionaires I have known, money just brings out the basic traits in them. If they were jerks before they had money, they are simply jerks with a billion dollars.", "Warren Buffett" ],
["Derivatives are financial weapons of mass destruction.", "Warren Buffett" ],
["If past history was all there was to the game, the richest people would be librarians.", "Warren Buffett" ],
["A public-opinion poll is no substitute for thought.", "Warren Buffett" ],
["I never attempt to make money on the stock market. I buy on the assumption that they could close the market the next day and not reopen it for five years.", "Warren Buffett" ],
["Your time is limited, so don't waste it living someone else's life. Don't be trapped by dogma - which is living with the results of other people's thinking. Don't let the noise of others' opinions drown out your own inner voice. And most important, have the courage to follow your heart and intuition.", "Steve Jobs" ],
["For the past 33 years, I have looked in the mirror every morning and asked myself: 'If today were the last day of my life, would I want to do what I am about to do today?' And whenever the answer has been 'No' for too many days in a row, I know I need to change something.", "Steve Jobs" ],
["Again, you can't connect the dots looking forward; you can only connect them looking backwards. So you have to trust that the dots will somehow connect in your future. You have to trust in something - your gut, destiny, life, karma, whatever. This approach has never let me down, and it has made all the difference in my life.", "Steve Jobs" ],
["Be a yardstick of quality. Some people aren't used to an environment where excellence is expected.", "Steve Jobs" ],
["If you haven't found it yet, keep looking. Don't settle. As with all matters of the heart, you'll know when you find it. And, like any great relationship, it just gets better and better as the years roll on.", "Steve Jobs" ],
["Being the richest man in the cemetery doesn't matter to me. Going to bed at night saying we've done something wonderful, that's what matters to me.", "Steve Jobs" ],
["Remembering that I'll be dead soon is the most important tool I've ever encountered to help me make the big choices in life. Because almost everything - all external expectations, all pride, all fear of embarrassment or failure - these things just fall away in the face of death, leaving only what is truly important.", "Steve Jobs" ],
["Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do. If you haven't found it yet, keep looking. Don't settle. As with all matters of the heart, you'll know when you find it.", "Steve Jobs" ],
["No one wants to die. Even people who want to go to heaven don't want to die to get there. And yet death is the destination we all share. No one has ever escaped it. And that is as it should be, because Death is very likely the single best invention of Life. It is Life's change agent. It clears out the old to make way for the new.", "Steve Jobs" ],
["You can't connect the dots looking forward; you can only connect them looking backwards. So you have to trust that the dots will somehow connect in your future. You have to trust in something - your gut, destiny, life, karma, whatever. This approach has never let me down, and it has made all the difference in my life.", "Steve Jobs" ],
["Sometimes when you innovate, you make mistakes. It is best to admit them quickly, and get on with improving your other innovations.", "Steve Jobs" ],
["Innovation distinguishes between a leader and a follower.", "Steve Jobs" ],
["My favorite things in life don't cost any money. It's really clear that the most precious resource we all have is time.", "Steve Jobs" ],
["Creativity is just connecting things. When you ask creative people how they did something, they feel a little guilty because they didn't really do it, they just saw something. It seemed obvious to them after a while. That's because they were able to connect experiences they've had and synthesize new things.", "Steve Jobs" ],
["That's been one of my mantras - focus and simplicity. Simple can be harder than complex: You have to work hard to get your thinking clean to make it simple. But it's worth it in the end because once you get there, you can move mountains.", "Steve Jobs" ],
["Design is not just what it looks like and feels like. Design is how it works.", "Steve Jobs" ],
["Sometimes life hits you in the head with a brick. Don't lose faith.", "Steve Jobs" ],
["I want to put a ding in the universe.", "Steve Jobs" ],
["Technology is nothing. What's important is that you have a faith in people, that they're basically good and smart, and if you give them tools, they'll do wonderful things with them.", "Steve Jobs" ],
["You can't just ask customers what they want and then try to give that to them. By the time you get it built, they'll want something new.", "Steve Jobs" ],
["Remembering that you are going to die is the best way I know to avoid the trap of thinking you have something to lose. You are already naked. There is no reason not to follow your heart.", "Steve Jobs" ],
["Stay hungry, stay foolish.", "Steve Jobs" ],
["Design is a funny word. Some people think design means how it looks. But of course, if you dig deeper, it's really how it works.", "Steve Jobs" ],
["Everyone here has the sense that right now is one of those moments when we are influencing the future.", "Steve Jobs" ],
["A lot of companies have chosen to downsize, and maybe that was the right thing for them. We chose a different path. Our belief was that if we kept putting great products in front of customers, they would continue to open their wallets.", "Steve Jobs" ]
]


quote_list.each do |quote, author|
  Quote.create( quote_text: quote, author: author )
end